---
- name: create ansible-dev-tools image with pip
  hosts: all
  gather_facts: true
  become: true
  vars:
    admin_password: 'ansible123!'
  tasks:
    - name: Install pip
      yum:
        name:
          - python3-pip
          - rsync
        state: present

    - name: Install passlib
      pip:
        name: passlib


    - name: Configure user 'rhel'
      ansible.builtin.user:
        name: rhel
        shell: /bin/bash
        password: "{{ 'ansible123!' | password_hash('sha512', 'mysecretsalt') }}"
        groups: wheel
        append: true

    - name: Create test directory
      ansible.builtin.file:
        path: /home/rhel/test
        state: directory
        owner: rhel
        group: rhel

    - name: Create test inventory
      ansible.builtin.copy:
        dest: /home/rhel/test/hosts
        content: |
          [rhel]
          node1 ansible_user=rhel ansible_password=ansible123!
        owner: rhel
        group: rhel

    - name: Create test playbook
      ansible.builtin.copy:
        dest: /home/rhel/test/test.yml
        content: |
          ---
          - name: test playbook
            hosts: rhel
        owner: rhel
        group: rhel

    - name: enable sshd password auth
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: '^PasswordAuthentication'
        line: >-
          PasswordAuthentication yes

    - name: restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted

## update the system
    - name: DNF update the system
      dnf:
        name:  "*"
        state: latest

    - name: install code server
      vars:
        username: "{{ ansible_user }}"
      include_role:
        name: "./roles/code_server"
        tasks_from: "codeserver.yml"

    # - name: remove dnf automatic
    #   package:
    #     name: dnf-automatic
    #     state: absent

    - name: Include common image cleanup tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/10_image_cleanup.yml"
        apply:
          tags:
            - image-cleanup
      tags:
        - image-cleanup


# Install python3.11 and set it as default
    - name: Install python3.11 and pip
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - python3.12-pip
        - python3.11-pip

    # - name: Configure alternatives to include Python 3.11
    #   ansible.builtin.command:
    #     cmd: "alternatives --install /usr/bin/python python /usr/bin/python3.11 2"

    # - name: Set Python 3.11 as the default
    #   ansible.builtin.command:
    #     cmd: "alternatives --set python /usr/bin/python3.11"


    # - name: set default python
    #   command: alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

    # - name: Set Python 3.11 as the default python3 using alternatives
    #   command: alternatives --set python3 /usr/bin/python3.11

    # - name: set default pip3 to pip3.11
    #   command: alternatives --install /usr/bin/pip pip /usr/bin/pip3.11 2

    # - name: set default pip2 to pip3.11
    #   command: alternatives --set pip /usr/bin/pip3.11


    - name: Verify default Python version
      command: python3 --version
      register: python_version

    - name: Display Python version
      debug:
        msg: "The default Python version is now: {{ python_version.stdout }}"

## Install pip3.11
    - name: install and upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3.11

    - name: pip install cowsay
      pip:
        name: cowsay
        state: present
        executable: pip3.11

## install ansible-dev-tools with pip3.11
    - name: pip install ansible-dev-tools
      pip:
        name: ansible-dev-tools==25.5.1
        state: present
        executable: pip3.11


## Execution environments
- name: Pull EEs in rhel user
  hosts: all
  become_user: rhel
  tasks:  
     - name: include red hat credential for registry.redhat.io
       include_vars:
         file: redhat_login.yml
          
     - name: Debug credentials
       debug:
         msg:
           username: "{{ redhat_username }}"
           password: "{{ redhat_password }}"
          
     - name: Login to redhat registry
       containers.podman.podman_login:
         username: "'{{ redhat_username }}'"
         password: "{{ redhat_password }}"
         registry: registry.redhat.io
          
     - name: Pull an image
       containers.podman.podman_image:
         name: "{{ item }}"
       loop:
         - registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest
         - registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest


